LOG_FORMAT = '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'

report_files = {
    'sample_report' : '',
    'snp_report' : '',
    'tree_report': '',
    'genotype_report': '',
}

SCHEME_HEADER = [
    'key',
    'mutation_key',
    'mutation_type',
    'dna_name',
    'gene',
    'gene_start',
    'gene_end',
    'cds_start',
    'cds_end',
    'aa_name',
    'aa_start',
    'aa_end',
    'is_silent',
    'is_cds',
    'is_frame_shift',
    'variant_start',
    'variant_end',
    'kmer_start',
    'kmer_end',
    'target_variant',
    'target_variant_len',
    'state',
    'ref_state',
    'alt_state',
    'kseq',
    'klen',
    'homopolymer_len',
    'kmer_entropy',
    'positive_genotypes',
    'partial_genotypes',
    'is_ambig_ok',
    'is_kmer_found',
    'is_kmer_length_ok',
    'is_kmer_unique',
    'is_valid'
]

KMER_FIELDS = {
    'key': 0,
    'mutation_key': '',
    'dna_name': '',
    'variant_start': -1,
    'variant_end': -1,
    'kmer_start': -1,
    'aa_name': '',
    'gene_name': '',
    'cds_start': -1,
    'cds_end': -1,
    'aa_start': -1,
    'aa_end': -1,
    'is_silent': False,
    'is_cds': False,
    'is_frame_shift': False,
    'target_variant': '',
    'target_variant_len': '',
    'mutation_type': '',
    'state': '',
    'kseq': '',
    'klen': 0,
    'homopolymer_len': 0,
    'ref_state': '',
    'alt_state': '',
    'entropy': -1,
    'positive_genotypes': [],
    'partial_genotypes': [],
}